name: Terraform Module Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  discover-modules:
    runs-on: ubuntu-latest
    outputs:
      module_paths: ${{ steps.set-matrix.outputs.module_paths }}
    steps:
      - uses: actions/checkout@v4
      
      - id: set-matrix
        run: |
          MODULES=$(find modules -type d -maxdepth 1 -mindepth 1 | jq -R -s -c 'split("\n")[:-1]')
          echo "module_paths=${MODULES}" >> $GITHUB_OUTPUT

  test:
    needs: discover-modules
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: true
      matrix:
        module_path: ${{ fromJson(needs.discover-modules.outputs.module_paths) }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.TEST_AWS_ACCOUNT_ID }}:role/github-actions-terraform-test
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Terraform Format Check
        id: fmt
        run: |
          cd ${{ matrix.module_path }}
          terraform fmt -check
          if [ $? -ne 0 ]; then
            echo "Terraform formatting check failed"
            exit 1
          fi

      - name: Terraform Init
        id: init
        run: |
          cd ${{ matrix.module_path }}
          terraform init
          if [ $? -ne 0 ]; then
            echo "Terraform initialization failed"
            exit 1
          fi

      - name: Terraform Validate
        id: validate
        run: |
          cd ${{ matrix.module_path }}
          terraform validate
          if [ $? -ne 0 ]; then
            echo "Terraform validation failed"
            exit 1
          fi

      - name: Run Checkov
        id: checkov
        run: |
          cd ${{ matrix.module_path }}
          checkov -d . --framework terraform --soft-fail false
          if [ $? -ne 0 ]; then
            echo "Checkov security checks failed"
            exit 1
          fi

      - name: Run Terraform Tests
        id: test
        run: |
          cd ${{ matrix.module_path }}
          terraform test
          if [ $? -ne 0 ]; then
            echo "Terraform tests failed"
            exit 1
          fi

  summary:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check Test Results
        run: |
          if [ "${{ needs.test.result }}" == "success" ]; then
            echo "All checks passed successfully!"
            exit 0
          else
            echo "One or more checks failed!"
            exit 1
          fi
